# Generated by Django 5.2.6 on 2025-12-01 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'excel_import',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('cluster_code', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('cluster_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cluster',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('college_code', models.CharField(max_length=10, unique=True)),
                ('college_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'college',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('unique_key', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('branch_id', models.CharField(max_length=2)),
                ('branch_name', models.CharField(max_length=255)),
                ('cluster', models.ForeignKey(db_column='cluster_id', on_delete=django.db.models.deletion.CASCADE, to='colleges.cluster')),
                ('college', models.ForeignKey(db_column='college_id', on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
            ],
            options={
                'db_table': 'branch',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cutoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('cutoff_2022_r1', models.CharField(blank=True, max_length=10, null=True)),
                ('cutoff_2022_r2', models.CharField(blank=True, max_length=10, null=True)),
                ('cutoff_2022_r3', models.CharField(blank=True, max_length=10, null=True)),
                ('cutoff_2023_r1', models.CharField(blank=True, max_length=10, null=True)),
                ('cutoff_2023_r2', models.CharField(blank=True, max_length=10, null=True)),
                ('cutoff_2023_r3', models.CharField(blank=True, max_length=10, null=True)),
                ('cutoff_2024_r1', models.CharField(blank=True, max_length=10, null=True)),
                ('cutoff_2024_r2', models.CharField(blank=True, max_length=10, null=True)),
                ('cutoff_2024_r3', models.CharField(blank=True, max_length=10, null=True)),
                ('cutoff_2025_r1', models.CharField(blank=True, max_length=10, null=True)),
                ('cutoff_2025_r2', models.CharField(blank=True, max_length=10, null=True)),
                ('cutoff_2025_r3', models.CharField(blank=True, max_length=10, null=True)),
                ('unique_key', models.ForeignKey(db_column='unique_key', on_delete=django.db.models.deletion.CASCADE, to='colleges.branch')),
            ],
            options={
                'db_table': 'cutoff',
                'managed': True,
                'unique_together': {('unique_key', 'category')},
            },
        ),
    ]
