# Generated by Django 5.2.6 on 2025-12-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fall_back', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
    ]
