# Generated by Django 5.2.6 on 2025-12-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='college_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
