# Generated by Django 5.2.6 on 2025-12-13 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCounter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'student_counter',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('student_user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type_of_student', models.CharField(choices=[('counselling', 'Counselling'), ('studying', 'Studying')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=10, null=True)),
                ('year_of_starting', models.IntegerField(blank=True, null=True)),
                ('college_code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=100, unique=True)),
                ('kcet_rank', models.IntegerField(blank=True, null=True)),
                ('hashed_password', models.CharField(db_column='hashed_password', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_completed', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('unique_key', models.ForeignKey(blank=True, db_column='unique_key', null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleges.branch')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'student',
                'managed': True,
            },
        ),
    ]
