# Generated by Django 5.2.6 on 2025-12-01 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellingChoice',
            fields=[
                ('choice_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_of_list', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('student_user_id', models.ForeignKey(db_column='student_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unique_key', models.ForeignKey(db_column='unique_key', on_delete=django.db.models.deletion.CASCADE, to='colleges.branch')),
            ],
            options={
                'db_table': 'counselling_choices',
                'managed': True,
                'unique_together': {('student_user_id', 'order_of_list'), ('student_user_id', 'unique_key')},
            },
        ),
    ]
