# Generated by Django 5.2.6 on 2025-12-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellingChoice',
            fields=[
                ('choice_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_of_list', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'counselling_choices',
                'managed': True,
            },
        ),
    ]
