# Generated by Django 5.2.6 on 2025-12-18 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMeeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('meet_link', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselling_user_id', models.ForeignKey(db_column='counselling_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='counselling_meetings', to=settings.AUTH_USER_MODEL)),
                ('studying_user_id', models.ForeignKey(db_column='studying_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='studying_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_meetings',
                'managed': True,
            },
        ),
    ]
