# Generated by Django 5.2.6 on 2025-12-13 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmeeting',
            name='counselling_user_id',
            field=models.ForeignKey(db_column='counselling_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='counselling_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentmeeting',
            name='studying_user_id',
            field=models.ForeignKey(db_column='studying_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='studying_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='studentmeeting',
            unique_together={('counselling_user_id', 'studying_user_id', 'scheduled_time')},
        ),
    ]
