# Generated by Django 5.2.6 on 2025-12-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('teaching_rating', models.SmallIntegerField()),
                ('courses_rating', models.SmallIntegerField()),
                ('library_rating', models.SmallIntegerField()),
                ('research_rating', models.SmallIntegerField()),
                ('internship_rating', models.SmallIntegerField()),
                ('infrastructure_rating', models.SmallIntegerField()),
                ('administration_rating', models.SmallIntegerField()),
                ('extracurricular_rating', models.SmallIntegerField()),
                ('safety_rating', models.SmallIntegerField()),
                ('placement_rating', models.SmallIntegerField()),
                ('teaching_review', models.TextField(blank=True)),
                ('courses_review', models.TextField(blank=True)),
                ('library_review', models.TextField(blank=True)),
                ('research_review', models.TextField(blank=True)),
                ('internship_review', models.TextField(blank=True)),
                ('infrastructure_review', models.TextField(blank=True)),
                ('administration_review', models.TextField(blank=True)),
                ('extracurricular_review', models.TextField(blank=True)),
                ('safety_review', models.TextField(blank=True)),
                ('placement_review', models.TextField(blank=True)),
                ('preferred_day', models.CharField(blank=True, max_length=100)),
                ('preferred_time', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'college_reviews',
                'managed': True,
            },
        ),
    ]
