# Generated by Django 5.2.6 on 2025-12-01 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('teaching_rating', models.SmallIntegerField()),
                ('courses_rating', models.SmallIntegerField()),
                ('library_rating', models.SmallIntegerField()),
                ('research_rating', models.SmallIntegerField()),
                ('internship_rating', models.SmallIntegerField()),
                ('infrastructure_rating', models.SmallIntegerField()),
                ('administration_rating', models.SmallIntegerField()),
                ('extracurricular_rating', models.SmallIntegerField()),
                ('safety_rating', models.SmallIntegerField()),
                ('placement_rating', models.SmallIntegerField()),
                ('teaching_review', models.TextField(blank=True)),
                ('courses_review', models.TextField(blank=True)),
                ('library_review', models.TextField(blank=True)),
                ('research_review', models.TextField(blank=True)),
                ('internship_review', models.TextField(blank=True)),
                ('infrastructure_review', models.TextField(blank=True)),
                ('administration_review', models.TextField(blank=True)),
                ('extracurricular_review', models.TextField(blank=True)),
                ('safety_review', models.TextField(blank=True)),
                ('placement_review', models.TextField(blank=True)),
                ('preferred_day', models.CharField(blank=True, max_length=100)),
                ('preferred_time', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('student_user_id', models.ForeignKey(db_column='student_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unique_key', models.ForeignKey(db_column='unique_key', on_delete=django.db.models.deletion.CASCADE, to='colleges.branch')),
            ],
            options={
                'db_table': 'college_reviews',
                'managed': True,
                'unique_together': {('student_user_id', 'unique_key')},
            },
        ),
    ]
