# Generated by Django 5.2.6 on 2025-12-13 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collegereview',
            name='student_user_id',
            field=models.ForeignKey(db_column='student_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collegereview',
            name='unique_key',
            field=models.ForeignKey(db_column='unique_key', on_delete=django.db.models.deletion.CASCADE, to='colleges.branch'),
        ),
        migrations.AlterUniqueTogether(
            name='collegereview',
            unique_together={('student_user_id', 'unique_key')},
        ),
    ]
